--
-- Generated by mysql-backup4j
-- https://github.com/SeunMatt/mysql-backup4j
-- Date: 12-3-2021 17:25:1
--

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

--
-- start  table dump : clients
--

CREATE TABLE IF NOT EXISTS `clients` (
  `id_client` int(11) NOT NULL AUTO_INCREMENT,
  `raison_sociale_client` varchar(100) NOT NULL,
  `adr_client` varchar(100) NOT NULL,
  `tel_client` varchar(10) NOT NULL,
  `sold_client` double NOT NULL,
  `date` date DEFAULT NULL,
  `commentaire_client` text NOT NULL,
  PRIMARY KEY (`id_client`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



--
-- end  table dump : clients
--



--
-- start  table dump : employes
--

CREATE TABLE IF NOT EXISTS `employes` (
  `id_employe` int(11) NOT NULL AUTO_INCREMENT,
  `nom_employe` varchar(100) NOT NULL,
  `adr_employe` varchar(100) NOT NULL,
  `tel_employe` varchar(10) NOT NULL,
  `date_entrer` date NOT NULL,
  `commentaire_emp` text NOT NULL,
  `salaire` double NOT NULL,
  `type_employe` enum('Barman','Restaurant') NOT NULL,
  PRIMARY KEY (`id_employe`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=latin1;



--
-- end  table dump : employes
--


--
-- Inserts of employes
--


/*!40000 ALTER TABLE `employes` DISABLE KEYS */;

--
-- start table insert : employes
--
INSERT INTO `employes`(`id_employe`, `nom_employe`, `adr_employe`, `tel_employe`, `date_entrer`, `commentaire_emp`, `salaire`, `type_employe`) VALUES 
(1, 'TAHAR LOUNNAS', '', '0771461406', '2018-09-24', '', '28000', 'Barman'),
(2, ' MUSTAPHA LOUNNAS', 'dem', '0795402513', '2018-09-24', '', '28000', 'Barman'),
(3, 'LYES KAYAD', 'dem', '0771277613', '2018-09-24', '', '28000', 'Barman'),
(4, 'CHABANE LOUNNAS', 'dem', '0771416101', '2018-09-24', '', '28000', 'Barman'),
(5, 'HAKIM ZAROUKI', 'dem', '0772254608', '2018-09-24', '', '28000', 'Restaurant'),
(6, 'YOUSEF OULMAS', 'dem', '0549311079', '2018-09-24', '', '28000', 'Restaurant'),
(7, 'HACENE BOUZID', 'dem', '0770404207', '2018-09-24', '', '28000', 'Restaurant'),
(8, 'SAMIR MADAH', 'dem', '0791977488', '2018-09-24', '', '28000', 'Restaurant');
--
-- end table insert : employes
--

/*!40000 ALTER TABLE `employes` ENABLE KEYS */;


--
-- start  table dump : entreproduit
--

CREATE TABLE IF NOT EXISTS `entreproduit` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `num_facture` int(11) NOT NULL,
  `id_fournisseur` int(11) NOT NULL,
  `des_prod` varchar(100) NOT NULL,
  `qte` int(11) NOT NULL,
  `prix_unit` double NOT NULL,
  `total` double NOT NULL,
  `date` date NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=226 DEFAULT CHARSET=latin1;



--
-- end  table dump : entreproduit
--


--
-- Inserts of entreproduit
--


/*!40000 ALTER TABLE `entreproduit` DISABLE KEYS */;

--
-- start table insert : entreproduit
--
INSERT INTO `entreproduit`(`id`, `num_facture`, `id_fournisseur`, `des_prod`, `qte`, `prix_unit`, `total`, `date`) VALUES 
(1, 0, 0, 'ALBRAU CAISSE 24CL', 116, '1200', '139200', '2018-09-25'),
(2, 0, 0, 'BEAUFORT CAISSE 24CL', 44, '1270', '55880', '2018-09-25'),
(3, 0, 0, 'HEINIKEN BTLS 25CL', 37, '2510', '92870', '2018-09-25'),
(4, 0, 0, 'BECKS JET 25CL', 17, '2180', '37060', '2018-09-25'),
(5, 0, 0, 'SAMBA CAISSE 24CL', 8, '1250', '10000', '2018-09-25'),
(6, 0, 0, 'ALBRAU JET 25CL', 12, '1540', '18480', '2018-09-25'),
(7, 0, 0, 'HEINEKEN PACK 33CL', 7, '2800', '19600', '2018-09-25'),
(8, 0, 0, 'HEINEKEN PACK 50 CL', 7, '3600', '25200', '2018-09-25'),
(9, 0, 0, 'SAMBA PACK 50C', 9, '2740', '24660', '2018-09-25'),
(10, 0, 0, 'ALBRAU PACK 50CL', 3, '2610', '7830', '2018-09-25'),
(11, 0, 0, 'BECKS PACK 50CL', 2, '3120', '6240', '2018-09-25'),
(12, 0, 0, 'KRONONBOURGU 1664 25CL ', 2, '3720', '7440', '2018-09-25'),
(13, 0, 0, 'GCO  KOUTOUBIA12*75CL', 10, '7020', '70200', '2018-09-26'),
(14, 0, 0, 'ALBRAU CAISSE 24CL', 100, '1200', '120000', '2018-09-26'),
(15, 0, 0, 'ALBRAU CAISSE 24CL', 15, '1200', '18000', '2018-09-26'),
(16, 0, 0, 'BEAUFORT CAISSE 24CL', 50, '1270', '63500', '2018-09-26'),
(17, 0, 0, 'HEINIKEN BTLS 25CL', 20, '2510', '50200', '2018-09-26'),
(18, 0, 0, 'BECKS JET 25CL', 15, '2180', '32700', '2018-09-26'),
(19, 0, 0, 'SAMBA JET 25CL', 5, '1580', '7900', '2018-09-26'),
(20, 0, 0, 'ALBRAU JET 25CL', 10, '1540', '15400', '2018-09-26'),
(21, 0, 0, 'KRONONBOURGU 1664 25CL ', 5, '3720', '18600', '2018-09-26'),
(22, 0, 0, 'GRIS D ALGERIE ONCV 12*75CL', 1, '5340', '5340', '2018-09-26'),
(23, 0, 0, 'WHISKY BALLANTINES 1L', 12, '1850', '22200', '2018-09-26'),
(24, 0, 0, 'ALBRAU CAISSE 24CL', 55, '1200', '66000', '2018-09-26'),
(25, 0, 0, 'BEAUFORT CAISSE 24CL', 20, '1270', '25400', '2018-09-26'),
(26, 0, 0, 'HEINIKEN BTLS 25CL', 30, '2510', '75300', '2018-09-26'),
(27, 0, 0, 'BECKS JET 25CL', 20, '2180', '43600', '2018-09-26'),
(28, 0, 0, 'ALBRAU JET 25CL', 10, '1540', '15400', '2018-09-26'),
(29, 0, 0, 'SAMBA JET 25CL', 5, '1580', '7900', '2018-09-26'),
(30, 0, 0, 'ALBRAU PACK 50CL', 5, '2610', '13050', '2018-09-26'),
(31, 0, 0, 'GCO  CUVEE TLEMCEN 12BTLS*50CL', 2, '3630', '7260', '2018-09-26'),
(32, 0, 0, 'GCO KOUTOUBIA 12*50CL', 1, '4620', '4620', '2018-09-26'),
(33, 0, 0, 'GCO ST AUGSTIN 12BTLS *50CL', 1, '4620', '4620', '2018-09-26'),
(34, 0, 0, 'GCO  CUVEE TLEMSEN 12BTLS*75CL', 2, '4860', '9720', '2018-09-26'),
(35, 0, 0, '33EXPORT BTLS33CL', 5, '1820', '9100', '2018-09-26'),
(36, 0, 0, 'KOELBERG BTLS 25CL', 5, '1760', '8800', '2018-09-26'),
(37, 0, 0, 'BEAUFORT CAISSE 24CL', 30, '1270', '38100', '2018-09-26'),
(38, 0, 0, 'HEINIKEN BTLS 25CL', 20, '2510', '50200', '2018-09-26'),
(39, 0, 0, 'BECKS JET 25CL', 10, '2180', '21800', '2018-09-26'),
(40, 0, 0, 'KRONONBOUGUE 1664 25CL5.5*20BTLS', 5, '3400', '17000', '2018-09-26'),
(41, 0, 0, 'ALBRAU JET 25CL', 10, '1540', '15400', '2018-09-26'),
(42, 0, 0, 'SAMBA JET 25CL', 10, '1580', '15800', '2018-09-26'),
(43, 0, 0, 'GCO  CUVEE TLEMSEN 12BTLS*75CL', 8, '4860', '38880', '2018-09-26'),
(44, 0, 0, 'GCO  KOUTLOUBIA 12*75C', 7, '7020', '49140', '2018-09-26'),
(45, 0, 0, 'GCO  CUVEE TLEMCEN 12BTLS*50CL', 3, '3630', '10890', '2018-09-26'),
(46, 0, 0, 'GCO KOUTOUBIA 12*50CL', 2, '4620', '9240', '2018-09-26'),
(47, 0, 0, 'ALBRAU CAISSE 24CL', 115, '1200', '138000', '2018-09-26'),
(63, 0, 0, 'WHISKY JACKE DANIAL 1L', 25, '3700', '92500', '2018-09-27'),
(64, 0, 0, 'ALBRAU CAISSE 24CL', 116, '1200', '139200', '2018-09-29'),
(61, 0, 0, 'WHISKY JOHNNY 1L', 10, '1850', '18500', '2018-09-27'),
(60, 0, 0, 'RICARD ', 5, '15600', '78000', '2018-09-27'),
(59, 0, 0, 'ONCV  FLUTE MERLO 75CL', 10, '6530', '65300', '2018-09-27'),
(58, 0, 0, 'HEINIKEN BTLS 25CL', 12, '2510', '30120', '2018-09-27'),
(57, 0, 0, '33EXPORT BTLS33CL', 10, '1820', '18200', '2018-09-27'),
(65, 0, 0, 'BEAUFORT CAISSE 24CL', 44, '1270', '55880', '2018-09-29'),
(66, 0, 0, 'KEINEKEN BTLS 25CL', 37, '2510', '92870', '2018-09-29'),
(67, 0, 0, 'BECKS JET  BTLS 25CL', 17, '2180', '37060', '2018-09-29'),
(68, 0, 0, 'SAMBA CAISSE 24CL', 8, '1250', '10000', '2018-09-29'),
(69, 0, 0, 'ALBRAU PACK JET 25CL', 12, '1540', '18480', '2018-09-29'),
(70, 0, 0, 'HEINEKEN BTLSCL 33', 7, '2800', '19600', '2018-09-29'),
(71, 0, 0, 'HEINEKEN CANETTE PACK 50CL', 7, '3600', '25200', '2018-09-29'),
(72, 0, 0, 'SAMBA CANETTE PACK 50CL', 9, '2740', '24660', '2018-09-29'),
(73, 0, 0, 'ALBRAU CANETTE  PACK 50CL', 3, '2610', '7830', '2018-09-29'),
(74, 0, 0, 'BECKS PACK CANETTE 50CL', 2, '2800', '5600', '2018-09-29'),
(75, 0, 0, 'KRONOBOURG( 1664) *24BTLS', 2, '3720', '7440', '2018-09-29'),
(76, 0, 0, 'GCO CUVEE TELEMECEN 12BTLLS*75C', 8, '4860', '38880', '2018-09-29'),
(77, 0, 0, 'GCO KOUTOUBIA 12*75CL', 7, '7020', '49140', '2018-09-29'),
(78, 0, 0, 'GCO CUVEE TELMECEN 12*50CL', 3, '3630', '10890', '2018-09-29'),
(79, 0, 0, 'GCO KOUTOUBIA 12*50CL', 2, '4620', '9240', '2018-09-29'),
(80, 0, 0, 'ALBRAU CAISSE 24CL', 115, '1200', '138000', '2018-09-30'),
(81, 0, 0, 'BEAUFORT CAISSE 24CL', 50, '1270', '63500', '2018-09-30'),
(82, 0, 0, 'KEINEKEN BTLS 25CL', 20, '2510', '50200', '2018-09-30'),
(83, 0, 0, 'BECKS JET  BTLS 25CL', 15, '2180', '32700', '2018-09-30'),
(84, 0, 0, 'SAMBA PACK JTL  25CL*24', 5, '1580', '7900', '2018-09-30'),
(85, 0, 0, 'ALBRAU PACK JTL 25CL*24', 10, '1540', '15400', '2018-09-30'),
(86, 0, 0, 'KRONOBOURG( 1664) *24BTLS', 5, '3720', '18600', '2018-09-30'),
(87, 0, 0, 'GCO KOUTOUBIA 12*50CL', 2, '4620', '9240', '2018-09-30'),
(88, 0, 0, 'ALBRAU CAISSE 24CL', 55, '1200', '66000', '2018-09-30'),
(89, 0, 0, 'BEAUFORT CAISSE 24CL', 20, '1270', '25400', '2018-09-30'),
(90, 0, 0, 'KEINEKEN BTLS 25CL', 20, '2510', '50200', '2018-09-30'),
(91, 0, 0, 'BECKS JET  BTLS 25CL', 20, '2180', '43600', '2018-09-30'),
(92, 0, 0, 'ALBRAU PACK JTL 25CL*24', 10, '1540', '15400', '2018-09-30'),
(93, 0, 0, 'SAMBA PACK JTL  25CL*24', 5, '1580', '7900', '2018-09-30'),
(94, 0, 0, 'ALBRAU CANETTE  PACK 50CL', 5, '2610', '13050', '2018-09-30'),
(95, 0, 0, 'GCO KOUTOUBIA 12*75CL', 2, '7020', '14040', '2018-09-30'),
(96, 0, 0, 'GCO CUVEE TELMECEN 12*50CL', 1, '3630', '3630', '2018-09-30'),
(97, 0, 0, 'GCO KOUTOUBIA 12*50CL', 1, '4620', '4620', '2018-09-30'),
(98, 0, 0, 'GCO ST-AUGSTIN BTLS 12*50CL', 1, '4620', '4620', '2018-09-30'),
(99, 0, 0, '33 EXPORT  CAISSE 33CL', 5, '1820', '9100', '2018-09-30'),
(100, 0, 0, 'KOELBERG JET BTLS', 5, '1760', '8800', '2018-09-30'),
(101, 0, 0, 'GCO CUVEE TELEMECEN 12BTLLS*75C', 2, '4860', '9720', '2018-09-30'),
(102, 0, 0, 'SIDI BRAHIM 6*75CL', 2, '4800', '9600', '2018-09-30'),
(103, 0, 0, 'ALBRAU CAISSE 24CL', 55, '1200', '66000', '2018-09-30'),
(104, 0, 0, 'BEAUFORT CAISSE 24CL', 30, '1270', '38100', '2018-09-30'),
(105, 0, 0, 'KEINEKEN BTLS 25CL', 20, '2510', '50200', '2018-09-30'),
(106, 0, 0, 'BECKS JET  BTLS 25CL', 15, '2180', '32700', '2018-09-30'),
(107, 0, 0, 'SAMBA PACK JTL  25CL*24', 10, '1580', '15800', '2018-09-30'),
(108, 0, 0, 'ALBRAU CANETTE  PACK 50CL', 5, '2610', '13050', '2018-09-30'),
(109, 0, 0, 'ALBRAU PACK JTL 25CL*24', 5, '1540', '7700', '2018-09-30'),
(110, 0, 0, 'GCO CUVEE TELEMECEN 12BTLLS*75C', 2, '4860', '9720', '2018-09-30'),
(111, 0, 0, 'GCO CUVEE TELMECEN 12*50CL', 2, '3630', '7260', '2018-09-30'),
(112, 0, 0, 'GCO COTEAUX DE MASCARA 12*75CL', 2, '6120', '12240', '2018-09-30'),
(113, 0, 0, 'WHISKY JOHNNY WALKER', 12, '1850', '22200', '2018-09-30'),
(114, 0, 0, 'ALBRAU CAISSE 24CL', 50, '1200', '60000', '2018-09-30'),
(115, 0, 0, 'KEINEKEN BTLS 25CL', 10, '2510', '25100', '2018-09-30'),
(116, 0, 0, 'BECKS JET  BTLS 25CL', 10, '2180', '21800', '2018-09-30'),
(117, 0, 0, 'ALBRAU CANETTE  PACK 50CL', 5, '2610', '13050', '2018-09-30'),
(118, 0, 0, 'ALBRAU PACK JTL 25CL*24', 5, '1540', '7700', '2018-09-30'),
(119, 0, 0, 'ONCV MEDEA NV AVIS ', 5, '5880', '29400', '2018-09-30'),
(120, 0, 0, 'GCO COTEAUX DE MASCARA 12*75CL', 2, '6120', '12240', '2018-09-30'),
(121, 0, 0, 'JET 27 BTLS 1', 2, '1800', '3600', '2018-09-30'),
(122, 0, 0, 'JET 31 BTLS 1', 3, '1900', '5700', '2018-09-30'),
(123, 0, 0, 'WHISKY G&B BTLS 1', 12, '1950', '23400', '2018-09-30'),
(124, 0, 0, 'JACK DANIAL 1L ', 4, '3800', '15200', '2018-09-30'),
(125, 0, 0, 'RICARD', 8, '1300', '10400', '2018-09-30'),
(126, 0, 0, 'WHISKY JOHNNY WALKER', 24, '1850', '44400', '2018-10-05'),
(127, 0, 0, 'RICARD', 24, '1300', '31200', '2018-10-05'),
(128, 0, 0, 'JACK DANIAL 1L ', 24, '3800', '91200', '2018-10-05'),
(129, 0, 0, 'JET 27 BTLS 1', 24, '1800', '43200', '2018-10-05'),
(130, 0, 0, 'JET 31 BTLS 1', 24, '1900', '45600', '2018-10-05'),
(131, 0, 0, 'BECKS PACK CANETTE 50CL', 96, '116', '11136', '2018-10-05'),
(132, 0, 0, 'HEINEKEN BTLSCL 33', 250, '116', '29000', '2018-10-05'),
(133, 0, 0, 'BEAUFORT CAISSE 24CL', 1200, '52', '87360', '2018-11-02'),
(134, 0, 0, 'ALBRAU CAISSE 24CL', 1680, '50', '84000', '2018-11-02'),
(135, 0, 0, 'SAMBA CAISSE 24CL', 1200, '52', '62400', '2018-11-02'),
(136, 0, 0, 'KEINEKEN BTLS 25CL', 720, '104', '74880', '2018-11-02'),
(137, 0, 0, 'KRONOBOURG( 1664) *24BTLS', 240, '170', '40800', '2018-11-02'),
(138, 0, 0, 'BECKS JET  BTLS 25CL', 240, '91', '21840', '2018-11-02'),
(139, 0, 0, 'ALBRAU CANETTE  PACK 50CL', 120, '109', '13080', '2018-11-02'),
(140, 0, 0, 'BEAUFORT CANNET 50CL', 120, '116.66', '13999.199999999999', '2018-11-02'),
(141, 0, 0, 'SAMBA CANETTE PACK 50CL', 120, '114', '13680', '2018-11-02'),
(142, 0, 0, 'SAMBA PACK JTL  25CL*24', 2400, '66', '158400', '2018-11-02'),
(143, 0, 0, 'ALBRAU PACK JTL 25CL*24', 240, '64', '15360', '2018-11-02'),
(144, 0, 0, 'BEAUFORT JTB 25CL PACK 24', 120, '6750', '810000', '2018-11-02'),
(145, 0, 0, 'WHISKY G&B BTLS 1', 12, '1950', '23400', '2018-11-02'),
(146, 0, 0, 'WHISKY JOHNNY WALKER', 12, '1850', '22200', '2018-11-02'),
(147, 0, 0, 'BEAUFORT CAISSE 24CL', 1200, '52', '62400', '2018-11-14'),
(148, 0, 0, 'ALBRAUT CAISSE 24CL', 1680, '120000', '201600000', '2018-11-14'),
(149, 0, 0, 'SAMBA CAISSE 24CL', 1200, '52', '62400', '2018-11-14'),
(150, 0, 0, 'KEINEKEN BTLS 25CL', 720, '104', '74880', '2018-11-14'),
(151, 0, 0, 'KRONOBOURG( 1664) *24BTLS', 120, '170', '20400', '2018-11-14'),
(152, 0, 0, 'BECKS JET  BTLS 25CL', 120, '91', '10920', '2018-11-14'),
(153, 0, 0, 'ALBRAU CANETTE  PACK 50CL', 120, '109', '13080', '2018-11-14'),
(154, 0, 0, 'BEAUFORT CANNET 50CL', 120, '116.66', '13999.199999999999', '2018-11-14'),
(155, 0, 0, 'SAMBA CANETTE PACK 50CL', 120, '114', '13680', '2018-11-14'),
(156, 0, 0, 'SAMBA PACK JTL  25CL*24', 1200, '66', '79200', '2018-11-14'),
(157, 0, 0, 'ALBRAU PACK JTL 25CL*24', 1200, '64', '76800', '2018-11-14'),
(158, 0, 0, 'BEAUFORT JTB 25CL PACK 24', 120, '6750', '810000', '2018-11-14'),
(159, 0, 0, 'WHISKY G&B BTLS 1', 12, '1950', '23400', '2018-11-14'),
(160, 0, 0, 'WHISKY JOHNNY WALKER', 12, '1850', '22200', '2018-11-14'),
(161, 0, 0, 'SAMBA CAISSE 24CL', 1920, '52', '99840', '2018-11-14'),
(162, 0, 0, 'ALBRAUT CAISSE 24CL', 1440, '120000', '172800000', '2018-11-14'),
(163, 0, 0, 'BEAUFORT CAISSE 24CL', 1440, '52', '74880', '2018-11-14'),
(164, 0, 0, 'KEINEKEN BTLS 25CL', 480, '104', '49920', '2018-11-14'),
(165, 0, 0, 'ALBRAU PACK JTL 25CL*24', 240, '64', '15360', '2018-11-14'),
(166, 0, 0, 'SAMBA PACK JTL  25CL*24', 240, '66', '15840', '2018-11-14'),
(167, 0, 0, 'KRONOBOURG( 1664) *24BTLS', 120, '170', '20400', '2018-11-14'),
(168, 0, 0, 'GCO CUVEE TELEMECEN 12BTLLS*75C', 60, '405', '24300', '2018-11-14'),
(169, 0, 0, 'GCO KOUTOUBIA 12*50CL', 24, '385', '9240', '2018-11-14'),
(170, 0, 0, 'SAMBA CAISSE 24CL', 1920, '52', '99840', '2018-11-14'),
(171, 0, 0, 'ALBRAUT CAISSE 24CL', 1200, '1200', '1440000', '2018-11-14'),
(172, 0, 0, 'BEAUFORT CAISSE 24CL', 1200, '52', '62400', '2018-11-14'),
(173, 0, 0, 'KEINEKEN BTLS 25CL', 480, '104', '49920', '2018-11-14'),
(174, 0, 0, 'SAMBA PACK JTL  25CL*24', 240, '66', '15840', '2018-11-14'),
(175, 0, 0, 'ALBRAU CANETTE  PACK 50CL', 120, '109', '13080', '2018-11-14'),
(176, 0, 0, 'GCO CUVEE TELEMECEN 12BTLLS*75C', 60, '405', '24300', '2018-11-14'),
(177, 0, 0, 'ONCV MEDEA NV AVIS ', 24, '510', '12240', '2018-11-14'),
(178, 0, 0, 'GCO KOUTOUBIA 12*50CL', 24, '385', '9240', '2018-11-14'),
(179, 0, 0, 'SAMBA CAISSE 24CL', 2400, '52', '124800', '2018-11-14'),
(180, 0, 0, 'ALBRAUT CAISSE 24CL', 1200, '1200', '1440000', '2018-11-14'),
(181, 0, 0, 'KEINEKEN BTLS 25CL', 720, '104', '74880', '2018-11-14'),
(182, 0, 0, 'BEAUFORT CAISSE 24CL', 720, '52', '37440', '2018-11-14'),
(183, 0, 0, 'BECKS JET  BTLS 25CL', 240, '91', '21840', '2018-11-14'),
(184, 0, 0, '33 EXPORT  CAISSE 33CL', 120, '79', '9480', '2018-11-14'),
(185, 0, 0, 'SAMBA PACK JTL  25CL*24', 264, '66', '17424', '2018-11-14'),
(186, 0, 0, 'ALBRAU CANETTE  PACK 50CL', 120, '109', '13080', '2018-11-14'),
(187, 0, 0, 'SAMBA CANETTE PACK 50CL', 120, '114', '13680', '2018-11-14'),
(188, 0, 0, 'GCO CUVEE TELEMECEN 12BTLLS*75C', 36, '405', '14580', '2018-11-14'),
(189, 0, 0, 'GCO KOUTOUBIA 12*50CL', 24, '385', '9240', '2018-11-14'),
(190, 0, 0, 'GCO ST-AUGSTIN BTLS 12*50CL', 24, '770', '18480', '2018-11-14'),
(191, 0, 0, 'ONCV GRIS D ALGERIE ', 12, '445', '5340', '2018-11-14'),
(192, 0, 0, 'WHISKY JOHNNY WALKER', 24, '1850', '44400', '2018-11-14'),
(193, 0, 0, 'JET 31 BTLS 1', 6, '1900', '11400', '2018-11-14'),
(194, 0, 0, 'BEAUFORT CAISSE 24CL', 480, '52', '1040', '2018-11-15'),
(195, 0, 0, 'SAMBA CAISSE 24CL', 2880, '52', '6240', '2018-11-15'),
(196, 0, 0, 'ALBRAUT CAISSE 24CL', 960, '1200', '48000', '2018-11-15'),
(197, 0, 0, 'KEINEKEN BTLS 25CL', 480, '104', '2080', '2018-11-15'),
(198, 0, 0, 'SAMBA PACK JTL  25CL*24', 240, '66', '660', '2018-11-15'),
(199, 0, 0, 'BECKS JET  BTLS 25CL', 480, '91', '1820', '2018-11-15'),
(200, 0, 0, 'ALBRAU PACK JTL 25CL*24', 240, '64', '640', '2018-11-15'),
(201, 0, 0, 'GCO KOUTOUBIA 12*75CL', 24, '585', '1170', '2018-11-15'),
(202, 0, 0, 'GCO ST-AUGSTIN BTLS 12*50CL', 24, '770', '1540', '2018-11-15'),
(203, 0, 0, 'GCO CUVEE TELEMECEN 12BTLLS*75C', 36, '405', '1215', '2018-11-15'),
(204, 0, 0, 'GCO COTEAUX DE MASCARA 12*75CL', 36, '510', '1530', '2018-11-15'),
(205, 0, 0, 'WHISKY G&B BTLS 1', 12, '1950', '23400', '2018-11-15'),
(206, 0, 0, 'WHISKY BALLANTINES BTLS 1L', 12, '1850', '22200', '2018-11-15'),
(207, 0, 0, 'JACK DANIAL 1L ', 12, '3800', '45600', '2018-11-15'),
(208, 0, 0, 'JET 27 BTLS 1', 5, '1800', '9000', '2018-11-15'),
(209, 0, 0, 'SAMBA CANETTE PACK 50CL', 120, '114', '13680', '2018-11-15'),
(210, 0, 0, 'ALBRAU CANETTE  PACK 50CL', 120, '109', '13080', '2018-11-15'),
(211, 0, 0, 'BEAUFORT CANNET 50CL', 120, '116', '13920', '2018-11-15'),
(212, 0, 0, 'BECKS PACK CANETTE 50CL', 48, '116', '5568', '2018-11-15'),
(213, 0, 0, 'HEINEKEN CANETTE PACK 50CL', 48, '150', '7200', '2018-11-15'),
(214, 0, 0, 'HEINEKEN BTLSCL 33', 48, '116', '5568', '2018-11-15'),
(215, 0, 0, 'ONCV MEDEA 98*50CL', 60, '270', '16200', '2018-11-15'),
(216, 0, 0, 'GCO ROSE FLEUR DABOUKIR 75CL', 12, '625', '7500', '2018-11-15'),
(217, 0, 0, 'BEAUFORT CAISSE 24CL', 10, '52', '520', '2018-11-24'),
(218, 0, 0, 'SAMBA CAISSE 24CL', 10, '52', '520', '2018-11-24'),
(220, 0, 0, 'WISKY 1L', 100, '1500', '150000', '2021-02-28'),
(221, 0, 0, 'MERLOT CASTEL 75CL', 50, '325', '16250', '2021-02-28'),
(222, 2021, 1, 'TEST 2021', 500, '150', '75000', '2021-03-12'),
(223, 2021, 1, 'ALBRAU PACK JTL 25CL*24', 150, '64', '9600', '2021-03-12'),
(224, 2021, 1, 'JET 31 BTLS 1', 80, '1900', '152000', '2021-03-12'),
(225, 2021, 1, 'GCO KOUTOUBIA 12*75CL', 130, '585', '76050', '2021-03-12');
--
-- end table insert : entreproduit
--

/*!40000 ALTER TABLE `entreproduit` ENABLE KEYS */;


--
-- start  table dump : factures
--

CREATE TABLE IF NOT EXISTS `factures` (
  `id_facture` int(11) NOT NULL AUTO_INCREMENT,
  `num_facture` int(11) NOT NULL,
  `date_facture` datetime NOT NULL,
  PRIMARY KEY (`id_facture`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=latin1;



--
-- end  table dump : factures
--


--
-- Inserts of factures
--


/*!40000 ALTER TABLE `factures` DISABLE KEYS */;

--
-- start table insert : factures
--
INSERT INTO `factures`(`id_facture`, `num_facture`, `date_facture`) VALUES 
(1, 0, '2019-04-02 21:13:22.0'),
(5, 190002, '2019-04-03 18:17:31.0'),
(6, 190006, '2019-04-03 18:22:33.0'),
(7, 190007, '2019-04-03 18:25:16.0');
--
-- end table insert : factures
--

/*!40000 ALTER TABLE `factures` ENABLE KEYS */;


--
-- start  table dump : fournisseurs
--

CREATE TABLE IF NOT EXISTS `fournisseurs` (
  `id_four` int(11) NOT NULL AUTO_INCREMENT,
  `raison_sociale_four` varchar(50) DEFAULT NULL,
  `adr_four` varchar(20) DEFAULT NULL,
  `tel_four` varchar(20) DEFAULT NULL,
  `solde_four` double NOT NULL,
  `date` date NOT NULL DEFAULT '2018-08-12',
  `commentaire_four` text NOT NULL,
  PRIMARY KEY (`id_four`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;



--
-- end  table dump : fournisseurs
--


--
-- Inserts of fournisseurs
--


/*!40000 ALTER TABLE `fournisseurs` DISABLE KEYS */;

--
-- start table insert : fournisseurs
--
INSERT INTO `fournisseurs`(`id_four`, `raison_sociale_four`, `adr_four`, `tel_four`, `solde_four`, `date`, `commentaire_four`) VALUES 
(1, 'DJAMEL MICHAL', 'boughni', '026231946/026231541', '100', '2021-03-12', ''),
(3, 'HWAMDI ', 'TIZI OUZOU', '026231548', '384830328.4', '2018-08-12', '');
--
-- end table insert : fournisseurs
--

/*!40000 ALTER TABLE `fournisseurs` ENABLE KEYS */;


--
-- start  table dump : lignesortie
--

CREATE TABLE IF NOT EXISTS `lignesortie` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `des_prod` varchar(100) NOT NULL,
  `qte` int(11) NOT NULL,
  `prix_vente` double NOT NULL,
  `total` double NOT NULL,
  `date` date NOT NULL,
  `employe` tinyint(4) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=140 DEFAULT CHARSET=latin1;



--
-- end  table dump : lignesortie
--


--
-- Inserts of lignesortie
--


/*!40000 ALTER TABLE `lignesortie` DISABLE KEYS */;

--
-- start table insert : lignesortie
--
INSERT INTO `lignesortie`(`id`, `des_prod`, `qte`, `prix_vente`, `total`, `date`, `employe`) VALUES 
(1, 'ALBRAU CAISSE 24CL', 88, '2640', '232320', '2018-09-25', 1),
(2, 'ALBRAU CAISSE 24CL', 88, '2640', '232320', '2018-09-25', 1),
(3, 'ALBRAU CAISSE 24CL', 88, '2640', '232320', '2018-09-26', 2),
(4, 'BEAUFORT CAISSE 24CL', 55, '2400', '132000', '2018-09-26', 2),
(5, 'BECKS JET 25CL', 17, '3360', '57120', '2018-09-26', 2),
(6, 'HEINIKEN BTLS 25CL', 41, '4080', '167280', '2018-09-26', 1),
(7, 'HEINIKEN BTLS 25CL', 17, '4080', '69360', '2018-09-26', 1),
(8, 'BEAUFORT CAISSE 24CL', 44, '2400', '105600', '2018-09-26', 1),
(9, 'ALBRAU PACK 50CL', 11, '4080', '44880', '2018-09-26', 1),
(10, 'ALBRAU CAISSE 24CL', 5, '2640', '13200', '2018-09-26', 3),
(11, 'BECKS JET 25CL', 14, '3360', '47040', '2018-09-26', 1),
(12, 'BECKS JET 25CL', 2, '3360', '6720', '2018-09-26', 1),
(13, 'HEINIKEN BTLS 25CL', 10, '4080', '40800', '2018-09-26', 2),
(14, 'ALBRAU JET 25CL', 40, '2640', '105600', '2018-09-26', 2),
(15, 'GCO  KOUTOUBIA12*75CL', 2, '1200', '2400', '2018-09-26', 3),
(16, 'ALBRAU JET 25CL', 20, '2640', '52800', '2018-09-26', 2),
(17, 'HEINIKEN BTLS 25CL', 31, '4080', '126480', '2018-09-26', 2),
(18, 'ALBRAU PACK 50CL', 11, '4080', '44880', '2018-09-26', 2),
(19, 'HEINEKEN PACK 50 CL', 2, '5280', '10560', '2018-09-26', 2),
(20, 'HEINEKEN PACK 33CL', 4, '4800', '19200', '2018-09-26', 2),
(42, 'HEINIKEN BTLS 25CL', 15, '4080', '40800', '2018-09-27', 1),
(43, 'WHISKY JACKE DANIAL 1L', 10, '9000', '90000', '2018-09-27', 2),
(23, '33EXPORT BTLS33CL', 75, '3360', '252000', '2018-09-28', 1),
(40, 'WHISKY JOHNNY 1L', 2, '4500', '4500', '2018-09-27', 3),
(39, 'BECKS PACK 50CL', 50, '4800', '240000', '2018-09-27', 3),
(38, 'KRONONBOUGUE 1664 25CL5.5*20BTLS', 20, '4400', '88000', '2018-09-27', 3),
(37, 'GCO  CUVEE TLEMCEN 12BTLS*50CL', 1, '800', '800', '2018-09-27', 1),
(36, 'HEINIKEN BTLS 25CL', 5, '4080', '20400', '2018-09-27', 1),
(35, 'ALBRAU CAISSE 24CL', 10, '2640', '26400', '2018-09-27', 1),
(34, '33EXPORT BTLS33CL', 5, '3360', '16800', '2018-09-27', 1),
(44, 'RICARD ', 5, '38400', '192000', '2018-09-27', 2),
(45, 'SAMBA JET 25CL', 75, '2640', '198000', '2018-09-27', 2),
(83, 'ALBRAU PACK JTL 25CL*24', 367, '110', '40370', '2018-10-01', 1),
(82, 'ALBRAU CAISSE 24CL', 1944, '110', '213840', '2018-10-01', 1),
(64, 'KRONOBOURG( 1664) *24BTLS', 17, '220', '3740', '2018-09-30', 2),
(63, 'BECKS JET  BTLS 25CL', 379, '140', '53060', '2018-09-30', 2),
(62, 'KEINEKEN BTLS 25CL', 949, '170', '161330', '2018-09-30', 2),
(61, 'BEAUFORT CAISSE 24CL', 1266, '100', '126600', '2018-09-30', 2),
(59, 'ALBRAU CAISSE 24CL', 1920, '110', '211200', '2018-09-30', 2),
(85, 'KEINEKEN BTLS 25CL', 949, '170', '161330', '2018-10-01', 1),
(84, 'BEAUFORT CAISSE 24CL', 1657, '100', '165700', '2018-10-01', 1),
(67, 'WHISKY JOHNNY WALKER', 12, '4000', '48000', '2018-09-30', 2),
(68, 'JET 27 BTLS 1', 2, '4000', '8000', '2018-09-30', 2),
(69, 'JACK DANIAL 1L ', 3, '8000', '24000', '2018-09-30', 2),
(70, 'ALBRAU CANETTE  PACK 50CL', 197, '170', '33490', '2018-09-30', 2),
(71, 'HEINEKEN CANETTE PACK 50CL', 44, '220', '9680', '2018-09-30', 2),
(72, 'HEINEKEN BTLSCL 33', 41, '200', '8200', '2018-09-30', 2),
(73, 'RICARD', 2, '3200', '6400', '2018-09-30', 2),
(74, 'ALBRAU CAISSE 24CL', 1944, '110', '213840', '2018-09-30', 2),
(86, 'BECKS JET  BTLS 25CL', 379, '140', '53060', '2018-10-01', 1),
(87, 'WHISKY JOHNNY WALKER', 12, '4000', '48000', '2018-10-01', 1),
(88, 'JET 27 BTLS 1', 2, '4000', '8000', '2018-10-01', 1),
(89, 'JACK DANIAL 1L ', 2, '8000', '16000', '2018-10-01', 1),
(90, 'ALBRAU CANETTE  PACK 50CL', 197, '170', '33490', '2018-10-01', 1),
(91, 'HEINEKEN CANETTE PACK 50CL', 44, '220', '9680', '2018-10-01', 1),
(92, 'HEINEKEN BTLSCL 33', 41, '200', '8200', '2018-10-01', 1),
(93, 'RICARD', 2, '3200', '6400', '2018-10-01', 1),
(94, 'ALBRAU CAISSE 24CL', 2154, '110', '236940', '2018-10-05', 2),
(95, 'BEAUFORT CAISSE 24CL', 1608, '100', '160800', '2018-10-05', 2),
(96, 'KEINEKEN BTLS 25CL', 796, '170', '135320', '2018-10-05', 2),
(97, 'BECKS JET  BTLS 25CL', 483, '140', '67620', '2018-10-05', 2),
(98, 'KRONOBOURG( 1664) *24BTLS', 56, '220', '12320', '2018-10-05', 2),
(99, 'ALBRAU PACK JTL 25CL*24', 587, '110', '64570', '2018-10-05', 2),
(100, 'ALBRAU CANETTE  PACK 50CL', 278, '170', '47260', '2018-10-05', 2),
(101, 'HEINEKEN CANETTE PACK 50CL', 41, '220', '9020', '2018-10-05', 2),
(102, 'HEINEKEN BTLSCL 33', 65, '200', '13000', '2018-10-05', 2),
(103, 'RICARD', 2, '3200', '6400', '2018-10-05', 2),
(104, 'WHISKY JOHNNY WALKER', 17, '4000', '68000', '2018-10-05', 2),
(105, 'JACK DANIAL 1L ', 1, '8000', '8000', '2018-10-05', 2),
(106, 'JET 27 BTLS 1', 4, '4000', '16000', '2018-10-05', 2),
(107, 'ALBRAU CAISSE 24CL', 9384, '110', '1032240', '2018-10-26', 3),
(110, 'ALBRAU CAISSE 24CL', 11064, '110', '1217040', '2018-11-12', 3),
(109, 'ALBRAU CAISSE 24CL', 11064, '110', '1217040', '2018-11-10', 3),
(111, 'BEAUFORT CAISSE 24CL', 4656, '100', '465600', '2018-11-12', 3),
(112, 'SAMBA CAISSE 24CL', 1208, '110', '132880', '2018-11-12', 3),
(113, 'KEINEKEN BTLS 25CL', 3288, '170', '558960', '2018-11-12', 3),
(114, 'HEINEKEN BTLSCL 33', 418, '200', '83600', '2018-11-12', 3),
(115, 'BECKS JET  BTLS 25CL', 2088, '140', '292320', '2018-11-12', 3),
(116, 'KOELBERG JET BTLS', 120, '140', '16800', '2018-11-12', 3),
(117, '33 EXPORT  CAISSE 33CL', 120, '140', '16800', '2018-11-12', 3),
(118, 'SAMBA CANETTE PACK 50CL', 336, '170', '57120', '2018-11-12', 3),
(119, 'ALBRAU CANETTE  PACK 50CL', 552, '170', '93840', '2018-11-12', 3),
(120, 'HEINEKEN CANETTE PACK 50CL', 168, '220', '36960', '2018-11-12', 3),
(121, 'KRONOBOURG( 1664) *24BTLS', 48, '220', '10560', '2018-11-12', 3),
(122, 'KRONOBOURG( 1664) *24BTLS', 408, '220', '89760', '2018-11-12', 3),
(123, 'GCO COTEAUX DE MASCARA 12*75CL', 48, '1200', '57600', '2018-11-12', 3),
(124, 'ONCV MEDEA NV AVIS ', 60, '1200', '72000', '2018-11-12', 3),
(125, 'GCO CUVEE TELEMECEN 12BTLLS*75C', 144, '1000', '144000', '2018-11-12', 3),
(126, 'GCO CUVEE TELMECEN 12*50CL', 72, '800', '57600', '2018-11-12', 3),
(127, 'SIDI BRAHIM 6*75CL', 2, '9000', '18000', '2018-11-12', 3),
(128, 'GCO KOUTOUBIA 12*50CL', 60, '800', '48000', '2018-11-12', 3),
(129, 'GCO ST-AUGSTIN BTLS 12*50CL', 6, '150', '900', '2018-11-12', 3),
(130, 'ALBRAU PACK JET 25CL', 288, '110', '31680', '2018-11-12', 3),
(131, 'BECKS PACK CANETTE 50CL', 144, '200', '28800', '2018-11-12', 3),
(132, 'SAMBA PACK JTL  25CL*24', 2880, '110', '316800', '2018-11-12', 3),
(133, 'ALBRAU PACK JTL 25CL*24', 960, '110', '105600', '2018-11-12', 3),
(134, 'GCO KOUTOUBIA 12*75CL', 108, '1200', '129600', '2018-11-12', 3),
(135, 'ONCV GRIS D ALGERIE ', 12, '120', '1440', '2018-11-12', 3),
(136, 'WHISKY JOHNNY WALKER', 48, '4000', '192000', '2018-11-12', 3),
(137, 'JET 27 BTLS 1', 26, '4000', '104000', '2018-11-12', 3),
(138, 'WISKY 1L', 10, '2000', '20000', '2021-02-28', 4),
(139, 'TEST 2021', 50, '200', '10000', '2021-03-12', 1);
--
-- end table insert : lignesortie
--

/*!40000 ALTER TABLE `lignesortie` ENABLE KEYS */;


--
-- start  table dump : preferences
--

CREATE TABLE IF NOT EXISTS `preferences` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL,
  `password` varchar(50) NOT NULL,
  `image` blob NOT NULL,
  `val_min_rupture` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;



--
-- end  table dump : preferences
--


--
-- Inserts of preferences
--


/*!40000 ALTER TABLE `preferences` DISABLE KEYS */;

--
-- start table insert : preferences
--
INSERT INTO `preferences`(`id`, `username`, `password`, `image`, `val_min_rupture`) VALUES 
(1, 'admin', 'd033e22ae348aeb5660fc2140aec35850c4da997', '?PNG

   IHDR   Ü   é   x3©­   gAMA  ±?üa   sRGB ®Îé   PLTE   WSR))($$#URQRMM//.???qpoeaa:9900/IHGBAA??>++*&"!<<:110765+**>>=@<:!  ,,+VVU<=:((\'UUSMMJBB@Z[[^^_?::®;;¹66r\'&?AAw,,Å89FWÿÿÿ  11/--+++)deW//-894))\'@@=þÿúAA?441330\'(%ÿÿþ<<:774561554HHFÿÿøCCA12-998abU>>=%%$

ÿÿü;<7ÿÿöûüï>?9$%"cdVôõè""!!!NNLEEDÿÿôKKJòóèþÿñJKFùúí?|ÿPNSSQefYÿCAãäØßàØPQN/0+z{wÿGEðñä÷øê]^PCD>¯°ªëìßrso???ÿLJÉÊÁçèßäåÜÞßÓÖ×Ðlliö÷îÒÒË¼½¶vws__\???ÐÑÇiifùúñüýôFGAÀÁºZZWÿWVîïâffdool??????«¬§ÕÖËÿTRÅÆ¿¶¶°\]Z²³®ÌÍÆÛÛÔ???ÚÛÏìíäÿZZôõìïðç??????_`R¹¹³éêâWWS???çèÛ???¨©¤???ÃÄºcda¦§¢ab^?"!¤¥?æ:8Ä10?  UUPÐ42hi\YZN?\'&Ö64ÍÎÁÊ214=Û75+
NOG#	Z¢((cë;:û@>¢£?¾/.ö><?$"à87º»®´µ¨?%$ð=; ¡?F???jÀÁ´q°,*¹.,???RwSTJÇÈ»µ-+§*)®¯¢?s¹¹·??z£¤?LwxlVWVlmaqre|¨©?ÿbd??????fg`ª+)??­+*  ?C30X\'&@$#hè   .tRNS <ëñ!-Ñ_¼UÑ?J?¨?«k?{?¼ãèsòÜæw¡áÀÊê?ÈéþgÅùÞî"°?û  8­IDATxÜ×]jã0Àñ&MÜ8I?H»í?}Xè?ldÇØ
?-Tá?º6?ºçÙGÜ`Aò~ügùêÿ~³_á?¯ßì?¯}µÍ_9}}µ©$b~¦»TN£xµðÒVK¸éÄ;ÚÍ} eM ¿Üøf[n+©JBã8ÞN|³M??#.õ,ÝâyÊ2?C¸uÓ;?lF¸?ºxGè ??6Bµ4yÅð? .?ùb_­??MI?-?>{b?=RZd¦¯EqÆí??\'¶?2.?Ò³8ÐÅ^¤?¯(%ºke??ìý?;lçØ??¡?Q\?PÄE¸t??ó¶É
lUf Üi*m9À9¿u÷Ø­¨eá??Ùr?n/Ý¶­·¥?w??Üaµpû©?¶$7m¯>tõ?®×Û?¦he?qQ"??p?«Ðe.ÛVªZtÔ¦KwØ/?}Nb7Rhe \Î-nt.÷Î¦[ü 8??Îû!\#F¸èîÚÉtám?%??p2¯õ%.Ü?£?3|8ÙDÝ¡­Ë¸NÊ²pV??Ò­Ý³=Æ?­âªNe"Ä #ßçò-pmëfq¡MçÒ?³8fÓYÌåaéÚo Ð?cRw};?\?¸óÒE÷ùö3tªÛj?IR?Z?Âå?CÝxéð¢À\???ê?6<&?q*«?F£®*pé¾]?ãÎ¡??I?b7\¸¬?Ë8o?q?M7?ËÝÛÆÞ?ÁCÙÓK?SÙ\êÎ¸ã×­#éî?ÔÚ?w²[SùauÏ?ºÝî·#¿¦v&??g
p½?©ÜÇ?Ó?nüÀ´÷òëvî?m?Ý(Ø*þ?z{i3Mã ?õ?ÄÚ?=Ow¦³;»=t:K?A?Í¤¤Á½Áh? 8"d¤7^íMÀÀ?K¯¼?Ë?Wâ4?? $VÅ¨H°*
z
a`$¨ûüß7ÏìûaìÂ~ëþ/?¥ÌÍ?ÿó<9ä³ÞA8JÀã°+"«?Y\'p|/mïnþ>v[-ÂF?âÎ?âXçe]¾:Æ?ÿßëÊEofiCqÀ?³Ûíy?VÇsiK\7?sÛ?üLâ?0?l{>²:âA??¢TW|ù?ÿúÆ¶ZÙì?£x?ã?»«3su?óV????çµ>Å?¡Î£ÚNê¼¤«%á???e#+ÉýÜÖÃ?Ü¿ÿøq©ñüõ?[Â6Qá(?Ãÿ
Ý3àPU÷âð(?\?[[ìDæ×æ?Ç?<|pÿq©ÉpîfÒ,lX8àØEâ(Ð¹??-L­ÍwvwwGùá?¾éî\\'`?éüÌ$÷ãÈÆ¸×¯_Óÿ%ò?dÉøõE0°þ¡ÈîîÅå\'ä3?¯×·:·Û«àØ??ÖZd{j­2¢±ìÇT?(pêáýÇ¦s`sJ?saã?xJq?;|4?Wi?iÃ¾?\'þ×¼"Øxá\\?d°!Ô?ýðh%:²ØÑ©­M?N Á?{òà÷NciEyÅÞëÒ2Ø¸¸.N?`\tÏ?b{tDØ¦?Im~ù>âÍ??¼_ò;<ñùÅ=z?Ñþç
ÃÇmw?rá¸8gç?£Pm?öGç;`cóØÇ4ð:×¢_VÏö¶W?yéK?WíúÿRôñïð¤?h¸&5g/?;<ZÚ????qª???cÊ»o<Û¯ùé?«Ö?CÃCCþø±ÿð6Ùxá¨8?J?çõáF2:E½1?uy??F³cäà,G³¼®Úý,ðv¨çÍp_ËÆÓm×,VeáÜmhîÛ£ìA?lóÀA§ð88?ìSªºÜ?¥g¶oe?º?ú?þ_î:>òåTy1?	/m??J¶1?l±\||dÅ§?Ç@?Z_?Îùåý/Ïª»[Öª:¯\'
½}åq?þDÅåOx(¹¸ç?B/Û[°?âTx?Ç@ùz×ÝÙ±8?<#?©ÌYE?c·÷÷¿mu¸Nªµ¨ÌgÍEÉÅ1NSÜáìÒ^||ynm?p¬£?¢SCÿL¶Î?ù¹xäö?\??b?Í½ýù?vW?¯ø\ÉE?èM¹&bå BÛVt|??SqÒÆQLø;?[?ÚzT~6Ãu¿ÏböâGz{­Åg»Px,?W}Nk?¶8õ?0OØF§FæÇ<Ð$UÇÿ&h°n9ºr?Yréi?µ?~|òÔmñ??»QìäâÎ?ß8­ÍQ³;X ¡8E­Qò[LLÚ??oí?Á#?EÅ6TWCÏÄXü«?páï?¯\ ¡´°??cãÏ?wÇö¢£Ç:??7?qàq?e°-ÎMÅ÷?þzY7îÆêêSÒU?«¬þwáæ¶K¦?ï(i(aS??8	ãæ?Ó+Û4?À©:¶	?¤0QÛ?´­?LÅ·ÇÒú«û<???¾¹iznëí½c,°p×?¸?Åq\;±äÖB\àPë´8¶°O??&¿?n\'³_?èÆ5?Îö´©É?·uuõVNÞ?[V1?UÒÆÅñÇ8?´Õ§?ö÷Gc	º?q°1N?lS£Ñ½ddö?n\[s8<?XM?­±±«²à?§}W?§1îp6¶"qS¬íñÎ!dS,?kYm?lñ?­d$UiÔ»sÍmmÍä£uëm,?+)ó;?k"Þ?ÔÈâ??y´q?±?½?(áX\'y¨®?/#@?a?p?4²?Ç£Û¹±Hú«R½×òno??½]?ß|Ó{õÄPÞlðYÕ?ãâØÆ¸??]?Õ??xÒG
Þ01??á@Ø?¤?Æ£{ûc??Ì?¸?Ïºzeh(¿i<?+/n?Å©çä?H?çx6»4¶¿µM8èNòDÐ{????dËSy[.¹ÛÈ\Ó?3^jì?¸6ÆqJ/ù}NyM4o?ÙÆ<?ÊTLà¤?yâÁ\'£)?C,??l|TØ¶öÇ?bé®?®ÜìbV®?w?íWÉÆ§??§RØ?SòÝy\'Ó?Kæh.?<Õ\'TÛb?\BF´m²%W"ÙtF÷?AÅ§dâô?/
%oãøg?u/$î Õ	ñ¸>	äpc\TdÑ²åÈ¶ÛM­ßÕ{QJï¥9QfÒ^J.NsNÈF¸ç?³¬§câG?=¡<öÈaË¤
?JÚÙÆ?"Ù?3À?.4¼$h?®5Pq8?
??#U+?»sf?Cu¤£½?}BÈaÓ?
0?åi+K?Ønzvòn?N?¡6¢?Ã??Í§y?üò¥8?ãâ0?­-è?³fÒÙÍ¥Ð¡<ÑÕH??qa¶\'iy[jgR_sÈçD?mà?Íæ·V)oW??Md³*·RS\??ÔÕOgÒ»±%ªn?t¢<ðàc!?W?iÛÊHl©ÙÌ?~Ü?6¢áfS?ÏYmV¾!*wúN-Î?âìÒö
?:Â­§vc©Ë?òÀ???jxÉx	v°?o-Ë
ÛúÄg%zqåa¢?ô±?:2»½ê599?²8iStÀmd	Ý~å?@*?ÂÅãÈ??L¶Fµ¥S³;ë?ÓwLºq??Db?Ç«Í/j]^?KÃ5?ÇSYçN×
[0?Nâ&gi.¥N?Ç>$ªÍ?`A¦ÒV-??¶ÌäÄL¥þOt¶§~??Js¹j	w/¢?.Ð?¢8^9?J±q-?&q-?³OOîPuR?òÀ# ?0r??EcdyZÞ6=sK¯ÍxÑ?Üê\Þzz¦ük·×}Kwõ©,NK9?v??­½ý·êï&vR¨:ð¨½???"ìI0?qk?í?¤a&\'&¦?½¢Wú?ÅL0;?F¨¯©ýÚíþÂ(_?rq*N)®!¢¨.08½>?Ú:æ?"?jr²ïÑø?äia?Ñ}O×ªké±>Ïí5ôL?Y¼?¯£8ÆñXb*ítNZÙFºü\:g&wfÓ4?Ì#?HHbÄI"B&iY¢¥$MÚ6¯tÚ*îyí??ö¾P¨/Øj¯y?¿åÃ½¼RÌSYÅ8±rò?`(?sY=3AÕåuð?þFrX%ab×P·FµÑ¾MÏÌÌ?ë³?\»Gôª½¸§\'Ôþ÷?µßãonè^?.?Mâ ÓNeAÜËÍéÉ?Ð> e???³"Y?,OK¡5Ð?mSßS§¦?üÉC´à?þá7ë	®ï­xò?>?ûÔ©Ôâ0??£ ?çõ©ºèv³ÂÇB5ÄaØ¿ÏÙò4²½¿©çLÝZèçÔ¾ÐPOÏ?ÐÏÏ_¾°øü?¶Õ;ãE?¿8«?ã??Å©84°PuR·±?L,?"dZ??mn¾ÿ¬HÇDÞ¾Z#Úpß+ÏË:??©KÜ1`ãN4??Ã???p??·w?t4?©4ù?(H5P?0Èx×@?¶÷?ëùËY¯#Ðò!4ôæhÁÀ3w?µ¡i5Aß?Ý1^·5?©ä?+??¼ 7çiz?3AºðÈÇÙUB Î\?A¦ì??½ÿé?IÇ_<W»êÅ)	?ú??×»Ì§6úìâ?b> §êÔ?¢DÒóO?ÓR7K>rÊ?
.À?Ø5È`û´ü¿ß·ëôÛ?ýù¿X;×?¨¯õßÇÖÖ»Õ¶v·þm­ç¿_?Ê?;÷?\Æé?+??Lg?Èpg`pR¹.?D@ä"÷Mx1Áä??dÎ+ßhH7iÎIHhâ¥ÇKK?/Î÷Yó?å,~3»?|·?ì¤Møôû¬çyÖo=kIÅ?þÓ?-¶?Î?èÀÖ|ìXuÐ)Q!!?¸òïN$9(W­FËdëòòr[[ÛkI££mmËË?ÿú¿ÿÛ?> úaÀäd@ûWæ¡ïpâ?Ç=V\-?s<Ë/ÂÊÐBkn??qÏO&´??u­3ÝÕeUU×¯?ßîëï¯llÌ?þÆ?Ê²Ütÿëßÿþ ¡°O??RÜõÆá45&?j÷ôå?ééÙÚ®ü?åHs	èt?T ?NÊï	ÇFÕdTÿëÿ?ÄB¹?¨·dcû|ó%?àRnUÀÊÄ«Ó]9ñ¡ÍÍ?ê¼ ÷?ÖAB??Þ(`Oð·n<ÆG?? ÃETÀÇr£¥?mó:?MpÌ¹«?kii!<Òt~Ôb¦:=?NÛ#j3ÂÃÃ36
×÷ÄÆèÜx(?C?ÉÈ?¦þö?Z?{BÓXB¡ÞdDÜ:Rí?,µz.çYD?FµvûæÍ????Í¦ûÃyßÜÊETÄ%#??¸ üû?÷¾Ó9øR?20?è°êHkkÓ³³³µPWQHºÖ9??iòÚë?×/õÝlÊØ\tá+è?Çì??Ca#?oéOIêôôwù¼°íýÅ?´?ãÁ©§sò?»jg??
ysø?xÜÑU¤Í6ö??ÕW\¿?»AºÊ/\ºoIÄ@
â\ ¹Òqd?wtó3Ý?è@§ º3EÎa?£ËápCNê6H§?Ã9ñ:ûDwiçÐ?²kåý£Ë¸Þ»àÌ?  AÈÅ?¢o2H6ÐÙwðèGÛ7uö¸;33od)+$(Ãô¨äN§Óó½?]HMMÉ)JHI¿·<Ð6Q:ÔQQ~3|CÖ5ÞZp«?· !2&FÅ#Ñ\'ÈH@l>òå?C»·¿µ??f¦?¸ÍÃý)ú?E²Ûí&Sj*MËÇÆ¥???1¶MZu?m3C=?û?¢7´êÊW

LyÞ?0	??1ücAéÙcyàJ?[%Ísû|¶í­Bt×?Ô?ÐæLÂÓb¨ý"?Ü³û)Ò=Ó À´ ¤?øY?Ñlm1ö´W×?7nlÕ5?=Y(X¸«Hÿö-¥Óßº°j?R?éJ F\'½P³nîý}voÛp?nû*%)"2«9½??3ß+é{$]SL.?.º¥?Åå´48?k­?Á{?e×û7?Ñý?O¿+X(piÕoÅ6fºõÝ©S\'NÜºp×eÒÇ)uP;¯?ËzoÏÇû7Æ÷iPT
¬?	ÊÉkÖá3ºgX!P¡Ä5©4v=1Ju\qºÖéÂ mMo[iGÅ?âÊ(ÿãÅw\'LsÆKÓ\( ÁÝºpáîÝU½f?È?627??MÙZðíÝÀ
< ??ÁG¡aÇð??,]³ndq,;?Aeg?BÜ??S¤©r°
]??º?ö+}®ä+Ï?ná?>$s#ñ¨Kv?((øî;rtÎeW 6éôI72??N«¥íÉ?ÿøèïà?È?xKÇé¨]k°®å·á??sss??G!åÙ??Ò¢û°ÕÐÚ~åÚ??Ë^ø
îªFþÆ¾¥ý.þaÀAÜºUXgK\'!mêF`?´³|ïÃ?ÿóÅ­/¤=ðéµYgXZ2S?[4×P?iS(²?ÂT?s´<(?ªèoúf??Îýí?D·°pb5.´Ä_4Ú?¦»§ÀElYWL??Dxsø,^\???ß_|²w?¸´Ð4Vâ°?ÎwºkwDÐbI:?Z?©KK?)Ö« gèî¸???²Aeô?þÙ?³t?j?«dQ¡q]ø?¨Ø/??¦ìt5	t%ypc2=fQ\¹ÇÿÃ×KK4¦G7?qÊ¦§³QT8MdV?ÚÓ%4ç?dgÛl?`?sæºÑî²BTñ?ÓõÝõüÃ[ =_(8q×¥)ÖÎ?? ù)ãL«woq"È;.É;f]p3±A?y¶¹PmHq\°*I=ùÃÝ~ðÒ`2^?`3N8?im?HÁ?éssÍ¶8À?\³5½÷ª«.Q?Û8ÝíûXw§¸y??I?Å?Æé¼&¬Sª9Ì³¡n)É±*UlT±¢ø?ý;|®9ÛR@û4?êÌîá£l³?tmÈ¾Ø­ªmºÌ±ØXÀ­g?,?Þ?ùûÊÓÂ?<h$ÎE?" àà?S¤ ö?æKÌSÅ%+Þû?¯mß£*Ùí|
7À´Z?|ýBNA|ªÑÇR²l°?v\ïO?~¸è?Üßÿ?èH??(?8?D\'®ºâtÞÂ??B®E/8²X²ç9Ü!?m)?,?H?VÑõmö9?f÷J?ÓiÅ«ÇTçrX-Ýeå7±Kºú?QhRÌy?s?ðÀ14Ê????1¯í-NLtÊ??ïx] UÆ4` L£*?é®¼¡,àºZzG;ëo7½?ÑxùÁËàeG;!Âá·Ü:{\?Wÿí¦ËF»?åW¬Ð~!£Ûõ9Vç"3Æ²?¨%Yd¦QBÉT,ªÕyÇõ¦¸8?«5®
pß¼µ?Ê§=/ ? FhLëS^ÉÃ´T?¼èÐgã?G|\y¢ýP?»?ÐóÏ-ÍAhK¤YRVXB^ß3?­Ea±?Sé»Ì½÷?ªn£¼½Âûë¾|ºÀ?D0ÎÆÁA&¹Kp?r :°÷§?î;¬?èl?Ø??\'ºØd?RþÜ?C?jZ?:µßø?GÅ?[MÏ?öVãtN?J?«û??ûf3Ê¨<;õÇ?@À¼ø #¦ÌSBNù»Ü÷2w<Âöé?9j°b!?ÚOåó^´?¤ÄDû&?? ÌUfå¥\é??¬éÒ«èßWÙ±æ~í¬¿¸MÑ5õ]{°?Ä"ãS?w%×|æqd?ðÔØdS`Åãj=³.[þð?ò,ÒÐ?È??|e±¯²Ö?²îÑº?a;?£:ç´ZÚº{Ê?O6k^ÙCàøÄó	\'X÷Õo?Ñß?Æ°?L?¯®1Ì:?p?%Ì#é%ø§²ñg?q¶ÑYÀö,\'ÕÜ>`1O??ã(\'?åÌ±)¸^	¸Í)º)÷2á½X`x´?ðÛ?w²Jë¸¶L§e?(>LÆP=ÀU?}È&?Yäª?ôî?Îk³]ÏòsN§Æ+-k]Ev?OÐè??ÕU}¬l66ûoL=\y?¢NhL¾½+á?uÇ¼ân×Átf6m)© c?¹~èaÇAÛRÛà\ªÈIßôôö??X?­.å$ ?F·Éà4¦ô_¥eå??f?yá?¿ oàÕÓç<ÿËNì??u"k£bÂb?U?ï¯/vG±.©}?¦±WôÎqQA
¥6`Q§ÄÛÒ4Ãæ?SÑnÕro¨â&ºÍ?^yñÆïþ?}ÏÞ?«n?ðµ?r
ÚG¬¨¤t??(;E¸ý??S1ôE7þ¨Ã,Qf µlÎSÓ®?Ã©Âô]5+¥=¼Òm:6Ïß¹öûý?½|ôây[z?N ?7aÂ?¥ý_Â:ún???ísý? ;?§ä¿?û??ÈX?2¢ôÀÅÓÕP7?UØônpÑÀ«üårýoþ\yùèé??7éóo­Û/?¦OÊ°.2éèb?b9 ëJè³Ù"µ)èSXûU?:?©?àíW?C?ïG|???;Köý±òòÉ#,@ ú?LqcGÖ?£½Ì:e`Ì?3a*U$ÿ?Ø¥?dJSÛ$ôÌ¬ùÊUÈáÂV[&K«ú±èÞY\'sïÜø?SàûkåÕ#8ø?ö°D#ÛÙñr`ÇªzãÌ¼E¶êðü¼?S?Sv8?î-VÔó²°bk.?Ã?Nÿ¼n¢¬/üÝÙ¢¡ð¦Ê??¯?ïÁ?¬¬¼b??È÷³Ëv? è4âÝãm_6»?=³?2¦,§ìÜ??ôàçû9?}u+º%ú:HÆ	p?}íÉ|Ï(ï?qòç\?ï¡ð	?Hÿ*?_¨?wWíÞ«úô?û( >FcÕÁ:_ç?;vîÚ¾mÿþ?>>®ÄÌíÎ?ÝÉRp?à:.n????ØTyîø~ÿ?üõ×ÊË?/? ÑÉA?wØ?E?t??j dó$øJ?¨ÌþD°Ndü:\')/x¥â KIpQÞÎ%¬Yæ;¶Ê9?Y22ÂÏ?ïF=??X?"FqïÂ]=V?Ø>Ú?rÐ×¾-?Dýiû??gJ?ÅÁQ?s?Ó7Xfzú¶?&	~üþü/w.ÃÀ²)d??
BÉGT}§ýëõÖ±ï?4Jp
íxÎuomK?ÑRg±[j]a ?s5ô¶Wõ\'n1?øã?ßÿpîâÙË×` H?"LJÆ­ÕuÖí^¤æ8ð¸N9æÿý¾ÿ²ZÆ?g&fFØìhâD¸°Uó`ç?Üp¤º-?;yòä??þôýù.Þñ ??{H?ÀCÅ¿¥GÂº°? ÷á=ËK?Îï ÜÎÿ6?¿nzÜ9±l?*?Ê?C?:[?:·Õp?`ÝO?ý|þÜ/0ð? ø\'??Ø.9íB>ÜqÀª%8ú9?íwÚû?ZÚÚ?®T?no5\-??ãk?èh_P÷°þ6?ø?Þjçôý÷??Ï½>XB R?Ñ?r?ÏÐEFaÎÅ*ÝûÛüEeËäëÒÇW®tÏOkõ*?Pâ8?Þñ´µóZ?Úl?2|Âý|þ?\øw?ñ1??À{	º®mÂ¢]ÊâÎ\?õ©¯k0?÷øÊãî×ô}!89Ù;,MÎiãrçµÛ?á[??ãÜy	ñÉüC?¸ÏÜ{??Òª?0·½O\'???Ó?ùI?»þÛ°<Ñù?Ee¢²ØNcw®Ú:ëÏö76/zK?ãkÎt?#:Â;+ÙÇÜct\'?m¿%HpñH(¨¡Gý-¹ºÑv2n~Ü8íRE½??I?Ó?ÑÎ?ëå}¹??á[@ÍáÁ&À?uð?èPÿXz?yD÷èùªw?²k?.Î·tÔ_!À??q¥£½æ.}pr±WBÑ?÷`¬¿ò$à¶Ô99?Ûº;?MOòd-ö+Ñº?û?Lp;wÈw!øÚÜ:_ú??e??s®®ãø|çTOÕåò~?U¢·>,½ã2?¬ÑÁ<¬<Ð!0_8iÕñ?ª89ë??Ú±C~z/ãòL7àfZV\'
$ÂÕÔLtWOUÁ;:?~ç¨äp??ç?ÎË:Ð?ç??¼|TàeÝ?OF«âÿÁ¹m¨r?ë~=n¼ZÅ£?%SN×Z&?ïµuT]FÎÜß \',:!¥?ÎË:ië°ë>~cÝ?l$¸±¾?\CïëöÎÇ?KÛzkfõÇ³¥&Á5\»??ôÁ_Û?Ê®æ6Á¹­`ãkN?­ó*	??Ö?½éý?	uÃÅÇEù?ÃvÇ<8Zruf?]?\¼.[9ºf?×XÆ-­.»~»)|+?lrç¤¸t\'LÁº)fÝ+³ó³7-
à¼?SÎg?«aù¤{¦ùÄäN???]?³êt¬=µ´Ît?a611zÓ`@ØxçÎqë.
«nJ²î»7???%¸@´_ñþáhÉX>)}=h±?b?8?)Ìd·\'9?\'GÛ¯Ô?chv?h¨Dã¼á?îo¬{áü¯7??%Úóx9·Ã×^îjå?34ä?"ÝQÉÃR£	ÓP±[{Z70S]_H=fôfªGãt@?ÃAÎMW(Zg?å9ùÞ¥%mÁÑ?#¸?;|?pXBp£??,i?Eh?UàC6k¶LT÷P¾Ìðq&ipëÑÎÛ9?àÄ?"O??þx?f? Åáä»UÚË?Y>i_îÅyª*Ê+,9?É¾ºf¦á½úË·o¢Åü;I&µDïÅ%%Ø¼?ãqÉé
A\'Y÷Ö=íúz§w?ÁÑÏéùÄØúºÔ?,kf]*),¸0;ÂÒØ;ZJp¹?ôãqÀ?P?¦?ÇS
à|[÷\'¬{~l¿Ô¿¿(9¸@åØ?>óÉÀL)õ\'¨³zU²Ü9?]¿ZÛb?ïì¨*¼Mí3WÆ[+Ü£?<?ø²î?Pë Ç¬Ã!?CêÁ¶¿GpT"É9Àíô±ä¦ë(Y²J`®=\,?[¾cÍX×Ö^]Vá?Û?$?`?O8È?u­<Z`?|ÇÎmï-i?bÃNÛía)?÷Õ.%¼¡??åP÷ü àôqäï¿ÜÇ?úÇl?aü×î+=?}¹?È?$?¤?7 )?AèÄtÉá?#ë?RP>Û¾÷ãOö|u?þ~IºÖg
ÓG)N?OZX²¢JÐÒ%?¥Pì.ç¬ÕØÛ?æ²þFyßÍÊ¦?ëD??Âå¨"°X"?Í?h¯¯ÖLï}?¥?L?~?Náè}+-MÈû$K?eûkrî?Ë¶èOÌXq0®ªp?MÐz>??~1äõâ?ñ?ÙxX²¸?·Ï<µÑC¸??ÞÂ?Ï¡?Laÿd?|n?*?ËÑH	?Ã?Ù]Ã³Ö.tÔW^è¸<?§oJ?â?è?Ø8/çÎÛº»"?Ð?U@ÓëÑã¤{lL??W1&£Û;mh?ÜPûëq?y¶(?à?N?CTO??¥S=×Ëo#,%5Éåõ???¥???Àæ3.A÷§3{o¼l¢ÒDØô.½	p ËV&\'kG0µø©,YZæ??·?o??8à¤M?½?¢rü^wG]7ëÏ­ät?R$ýñ\'9 áHdrIh?N^ê@w_?%Ù¦1?MoÇ6~XÌ??eiÇè?Ç}»Öoæê?±æ:»\'FÇ-5W?íq^Î?up[qKëÄPG7r½Ô¸^¾|ôä;(Áæ\'ÐU§¡fcµ?­¼]¥V±?ì1\¬ÐaxmýSZ_[ëZ_Ï´w?Î·?[?Ã	Á8FGp9?ëE?£OD·ûso??_Jü?Mß3:(?°?D0?s2¸Ë¥z¶ uF?ê«mcª»?Æl ·82?Ùå#û×?9«eptí¯?\'-Fk?TÅ?9¦?k­ÆI´^H?0.t\rÌ?Æ/Fèe# é???ð?Här?½YsÞM
èØµ?¾±?óØÀ?±?Y?¸¢pÞçFl?e?üÁºJ`5L?ÎÌ?¶öZj¬µ??Âó¥Ê8Ã8ÁÁ¸>?%ø$ÝÌ(ozCB $×	?þô½#ã¶Nt?æ?Ugf¾æt	¸¨éÄ¡?KÀéÔß®Ûõl??Ï#½?Ë£m­ãu???Z§)Î?QÜtä\]Äê \Áq	?¾0 ?¸MÇ¬»fV°/
´¹$´¸dEvs`?Óápê5q.sý?ÛÇ®?u½ã­­ã??³NëU?s?¶r­óCD?Dé*7?ó?Pþ¿4b#8)]?u¿_Mc\'ÄÛ???§K*"8??&+$¸¹Ýë÷E(ÐFCÝääd?ÅXÓ2ípÑ·=¯¸¤³??:À?U!YzÔÇåÏLFÉ?T& BXeDÅÉç¤¸Är[d,e©[?-S¡Ç<àL?S&?>[·?Ó?æ?2Ô?[®vå?â8è?\oëL5Á]"qB¨ëøA?Xå¨"?WB!¸ÑHÚ¶Å§h"Ðoa??Øæ2u©úÜC??erNöõÞÜo <?ÁXc¶âi½*R¢?bp®ár]3^?¸>A~(ByV=_	?h<*?îÎÊqºz?kUvºV6?v./=??ø 8úúOpp®ùËÖÕðÓ9Ï]µW[Ì55fs?3¥?^=pÜlÀµÕ?!t_ RüæZÏÈ?Ð-"?\'??Ë?³Õ)µXnÁ©ö3EEè·4±`Ó¥gFFxàXFq;gÛ».â½?ÒuÕj%6<jSK(Y¢?£¾¹Ë
¸	:	Á«!^*?{V å?¥h!??"ý?hdh?%7¨ÄT$^? H?$Ä?©^L	?s8_?k>º.&?=ºã?np?>1?§CÐµ/?Ø°SuN?QæÚ;±á©¸N*?Ë¥H|çè?GÞ?n9?Ä6???L9?÷v?õMl½?ÙJÔje
»¿ï$àXW?:\'ÂÑ#á§OÑã!?£§QhÀ÷x¨[­?%
®ÐC2??g9!cô^?¿ø.? ?+?àrëSBÓ s¦«?¡Å¢×¨?c	.pÜ9F*Ñ8p)Æ¢ðI?½µD?vä º¡0|`À??n?38XÇµ?ó2$³ÒãàE?ó?<ç`n4üï7íH(M¤ÆÇÆÓ ÐlÍé¸Fµ$g?ÙîËí"½¤?ú?ªÏ?w?³¶XQ?9HMzÖ,NxjãË÷Ú;«;Êê«?*d1}B $LôØxî?¸Ù?:[KwéÝúÐ vÿM?¡P?¯µ V#Ü9FÉJ=U"ì
 ?M:3Üuõ*ØÌfT?Ù.d¢áaÊ£V³/Ükï®¾ÒQÖS_@Q~0/{2Ä;??.z?cËQ$dh¤_ÎÝ?M§«eìjÍ(ãÿ)WW3?³Ø? x7Îe?6K?àl??p?!t?.èxJR=¸£±%¡¶W?g×À?Ç¢FgàÁqX¯U]!%@!©¢&\'??Bç¸X42tÖ?æ¾?%ÝÎÖ\¸u7+/@??½?ôg\´cMV°¨d¥?E\?¡½?G`Ò?{`C97âd%VCÝøÀèD)Áu?½??3B?ï?¤D	yB?"$??.þr±ìÕjñR?,?(U®4Ô¬M¤E\'Uu,9°\æ.$+t??°êP¤é=*éf3P©­¸¸¡ê+Së%õ?ä?b¶á? d?Ä@¹.?î\»ÿ×?çE3Ï4õìÂsÓ0Ã? ÇåÚÏÑ_ ?ÀÜ1q*óý¬4F?Tô?nõÔ°êµ?}FrÑR7Þº¸n¢55åE+P2#ÉC(@????òÉ?tóÜ?Fp«Ù¡KÀÙM¬?qy´*?nN??3à fÂºáÚi?«?\'<ít]ïà@ÛüD)ÑUA½!Âÿ_ÝùýDy¥q\g?á¨u×îþ	.Ãº???0B@??1LÂ?&DR³-½ nôfÓìÖVY?hÚÉ.½?À°hÈ\???ÞxÇM7Í?xe¢?F£l?%½Úï÷9ç}ç¤»Öö¾;Lf»[?ßçyÎyÏyßç??_JÐF¨CH0Ë¶Æ\'Ô.?~pÞ Cj¿qA?êE­\Ãc"???ÁU?<?­4xªã9G¸Ià}d4ã
Å¥iÒ}>W.©B*¢&£&b0ñ¢?>?À¸úóg÷~x¼y?LîÒ@²åÔ	°1(%ãÆ3çÆQ/û¯?ÁEÐ=%cÇ¥^^ÜÌÍÉ©üä,.ñf ?³ù?Âº¡sX*?i!?P-0ú?Àó3?
 Ò4.0¼³?çB/?ÉêÎh?·¥??A??Ck?VQà\¿s?ûn?.&õòê5	ËüTacr?ö-ÎNNâ¿??Å[·¦Á÷S²¤AH?T\'-¢¢	&Á¨¿~ýâ	?è¬\'¥²?	×ã?mkF³2Ä;]?Ó­P¯?ÎnÌ?®´^?Ú?}@ÌÃ¹Òzñ´T®ém(­?j¢¤
iÁÇ4tj?£/?ß?±]ÊâAÍ?aS)QMP*ûÇæ;:²+?s¼?6-g?`Otrúüà??b±P Þ$»=H·¾^Ä?ª¨"²Rû?Âh ?²êj?*?H y¯àþdN&[È?áÆÉ|s¤0{6?]Á¼sÄé$?Gð?{s¦ø?ç5ÎHfó%|ã"ÌÛÈó5¼©5eU0*?J?V1É$TDËhÉ§þÐçÃTï¬½xò?VÚf{Ð?Fq¾{·û+e?Æa|O ckf?Ó?(.÷¯w%°*x?·±~kt??)ò?n
oyjÒW^cÉj9$é!ÃÔÉDµÐ7?|®î³ïî?ûêd?IÂ?ý©ç->§Ù\'<7²pölë >?K¹Ý ± 8¬áP.p.Ì nizéVqVOÂs?Zt4+RTb*$	ÅC?}µÔ( ðÔ@g*4k?~Ü?u?Ikª?àCÃÖ¸ù±±ÁxßÉ¸Q·© <ÃóÚÙ??°8??,§A·¾^0d?Å¡úÈ×?ÑMÊ????ÌR!ôSÑ÷Ñ·?|PtôÙ×&0	wÃKv´qé?Wr??`YI?ETr\'¤Þmzß?Uj\¡sÏjNi?t°®¸^?¢2p?æ
u! +*E%%!IKJ¨.Õ??·w>¾·M·ób§ð±\É«.5Ã¯±Álª#?¨Ì?q7èZ;Ð¦tøiç`pY­cE?q°MÐÔ{¢}? J ÒÅ¼Æ©æ¢A,´Ê´xÿâ» ñ>?{O?l2ïúÚÒ-g?rWs«??q0n>vrËF¸Ús.VÙº?!Ç7?¯ýü¶?µ^2å¦òD3dÂtúÔÑejT!i#<Ôl??#?@?ÏàY>+ü?µïÐßáôûÒèEÐ³z?<Ý,\'?q½If\&Ã5g?ÒÂ^DgÀ?°Ä$õR?º?°Ñ(d?¥L??+?Èp
¤ÒBSÚ¨>J±±µÔ¯0ä³þi?!ô1?ÁþñÙ77æ?Å»Î?_æ#ú}??0ã0d;d \ÓG??b)ÂÑ=\ºc\.é8]ÞPÛàÈÀ,Ó¾4GM@9?×ìÔò²???â¢?©B*!i¡o ïß?M?+>^ðõwO_>¾týX2Ñóü?­	,¢Ó8o?Æ­ÄzãbÜÑº=®j?c?ðDy\'ëåmN?¯Ì 2ó³?´k Õ:?Únþ"~|	+@ÉD¸¨&ZH??yôù?wOí#?úGý?×x\'ÃÓû7ðØi¬óÝå­¹áÌ8ÇÜ?q¡6ÓïF%?¶ÐºNªý<Æñed¯¿Y$?`£g ?Ø¼TRuCoQC?dÎ2R5Pm¤* Ã§ö£??ÌÀ=Äãå«ã¸Û>q>w?[?6ãæ?£,?ý??TS?%?:ÕÞÃ?r?	ïf$$?×?oç&æVÁE&ô.¥Ó?þ{ks$P	ù6}Áh!?aj?Oíctö­?OÉÈ??£¾øÏí?MtÏÝ=qÒLN?qb®VûÝ}­?ÇSZ.qþ??aèð-?íÚ\'DCònpñÿ?¿?Çô´øêè?R¬JgÀ¨?s`ÌÁF?Ri"é`?É>Å{H<ðý?2l¸9êEß9,c¶ÅÏö??A9ã²4n?ÆÕWþd³ñX-8?B½ìÁP·½v?l´í*º«Ó´vÔTNC¥SX<??(??8$ýñ[d$¢¸HF@??Pù??ÇètÜmS6<?õ²ílãò}±	J×?5P?õÿ??n?Zº?Cð?83t?²Í½K´ÎS]Û­Ý<Ñ±cxyªt?W¿`Ô?¥R|D¤???>?î?NsÏ?°ý?c=ñØ?hl+Ðm+×?g×?qr)8wëÑZ?Å¯ûä??ÛH;)H7´·?x{h®-¦`JÔÖ?¿Å|ÐwÊ0&ãD$£úØm ¥?Qå+Ãcî*§E#?Ü£??¶YÂ?É<Ø2è??Å¯Ú(¹S/ß:Ð?ð»>/-Õe¸"VÖßêî9?N0ÇãiK¦,æÅWÛ6??²Ö??þ!8h?à1÷$õüØ|¨2¾?w9o±6í#ÛJ·?r2Þ¼Å=à7?N8M9ÿîsl?l±ÊI÷²Á6ô?Iûd
§"#??­ºÈÒhäfî²ÚgÝ?Òe([X¨??®¾??è^±Ý¬Á?M?&8?»QPUC?Ë1©gº±?	ó(ú&l`óÊ?>¤%µøx?|0?¸(Æ?	Á?àùtÓ??|Ô?|ã?>Ý2?¡µ]ioÂ??ñ1g?séð !??ðLÓÒ9 9???ÖôÍÿú??àºè¿?Î:?ÄOû?L?Ýx1æÍr	1PW?y÷4°}a?û¡h`Ë°#¤×{RËÉH¿3õrè?Cr?øÐ	Y»?òd?D,@ó? µGåXë»¨xO¦Ü3Á?Ü:N÷%ñH§3òÝ#?²-?í~û¸?ÂÌ??¾?jÜxÿÿ=?-Ã4Cøxï?¨«ã8É²??Nm?JÉ??C¡#ÑÚÚÆúú¦¦¦úhØãÿ èe*3?ó?7«??Þ)Ý?Ò	ÑÛ#y&~x?_ñ.?¾áî¾Þ¤àØÚ÷?Ö?É¶À ?Vi±?¨E^8zø?Æú?ßÖíß[?TWWU?_RõÞæÚ#Û|N.zò?Ã/NCÓ§»"tê?¿"A4²ýE?2?7ò­×?8?Áø*ú¥qh?Ëyå+Tuð?ýN?Ú?Ý@:=Ô\·7¢8?XQS$m=öß=¥csæµKçG¦à?oÿöÙ^>[ùv ?814?Ã=xfæ?0yõ1>?{ÃüJd|\'ý@¼,¸¨xu#úÊHÍ¡hØ/=J
:¹OUs»hjÞIÍ¤w:[Ñ?OEÓF??>9??çrÃ[«Ò^X?ûYÇ?T ??$2d ìg7Øg?îo"??êªJ í5EÅÐ-ùk×x$lÓ?â?IL?qM?ê¹Ô?lC5aÆ½:*¯®6­ß\'?céPm{MUhy?ÏZ×°?É]-?³:ÓÔÕ2hzh?íñ³Óóç2?ÇJ?9[sÒ¸?§ê?ÚÐ?Íz??Ö×°eù/QUÅÁZÚ ?3.;	ÇÉ­³?	ï?N?Ê¨¥¥[/?¶yzi=h?Þ?#Ø?Wó°×:¦jo?t?e?l¯ù_È·¿AÓÏR??ue?9èt?| Ã?à:j?e»81<:~?í?±² L¬è|Í¯Ç?¾/Þ×ØLË~µªë¬}p?·+âRN>B`Z:»bM°õR© ¶Y²½÷lsë«èå»pô¨Ì0ùófÝ/ù?Gö:åã×Ùw(ä±?®Õ?K-?Æ:¥S<·+òùû?7Áã¶NÏÝ½??½æýMo¼ùæáßÝ÷û?=;@?ÍQÔ*¦?Ü×ÛéXçÓq?,/?ÕS ?áàÛå¶®ÎÉRz4ÂÑ&R©¨Þ³S??ã`×#t9±.@·¨;*waäæ?Ç?íô?rcMÃ?ArJqx/!æÁ;µNéÌJ¼ êî?Y©ÚÜºz	?§@ø¬ÜNÒ$ðÈk!?²ÈÔ­ê&È?PJ>ÝD¾??[áÍ;?LÝcîûZºÏ?]9"?÷Í??Õ?Í?9aCP2ãv0ÞAàé°?ÊisoYø HB³??$B?ÛrðOp-h?ãy27|¬-Nåäê-À?Æ»æaöSù¬K¬¾j?Ã±rÑ?X<%>9Û$ nü?ËT°?÷&;Ýï|U
/0¡æè ËcX?§¸ýÂ]
D$Ñ½­¡;?L¯?ö?Q95SDlqOiø?c?X¼µ¹rÏ.QUÍátð?Á_­nIð?hn?J?S??Üù	çTÈ]®VÌ$7XDÜz	óÀ?]¥HC?@Îê?Õ?§??dãÑº]c?³tcùT??^¨?§(íBUí\'?»­¢?ÉÓõôôÀ]?\'W³?ñL?ð=?+f%ÛÅx?GÂ?(Å
í?66Ðw9^E]sS}môwÑ(Vçß¨o¨ÙyÍ¥?ÿSÄ?ñ?ýW(    IEND®B`?', 20);
--
-- end table insert : preferences
--

/*!40000 ALTER TABLE `preferences` ENABLE KEYS */;


--
-- start  table dump : produits
--

CREATE TABLE IF NOT EXISTS `produits` (
  `id_prod` int(11) NOT NULL AUTO_INCREMENT,
  `des_prod` varchar(50) NOT NULL,
  `prix_achat` double NOT NULL,
  `prix_vente` double NOT NULL,
  `unite` varchar(50) NOT NULL,
  `type` enum('Biere','Vin','Liqueur') NOT NULL,
  `qte_stock` int(11) NOT NULL,
  `fournisseur` varchar(100) NOT NULL,
  `commentaire_prod` text NOT NULL,
  `dateAjout` date NOT NULL,
  PRIMARY KEY (`id_prod`)
) ENGINE=InnoDB AUTO_INCREMENT=84 DEFAULT CHARSET=latin1;



--
-- end  table dump : produits
--


--
-- Inserts of produits
--


/*!40000 ALTER TABLE `produits` DISABLE KEYS */;

--
-- start table insert : produits
--
INSERT INTO `produits`(`id_prod`, `des_prod`, `prix_achat`, `prix_vente`, `unite`, `type`, `qte_stock`, `fournisseur`, `commentaire_prod`, `dateAjout`) VALUES 
(53, 'ALBRAU PACK JET 25CL', '64', '110', 'bouteille', 'Biere', 0, 'DJAMEL MICHAL', '', '2018-09-29'),
(54, 'BECKS PACK CANETTE 50CL', '116', '200', 'bouteille', 'Biere', 0, 'DJAMEL MICHAL', '', '2018-09-29'),
(55, 'GCO KOUTOUBIA 12*75CL', '585', '1200', 'bouteille', 'Vin', 130, 'DJAMEL MICHAL', '', '2018-09-29'),
(56, 'SAMBA PACK JTL  25CL*24', '66', '110', 'bouteille', 'Biere', 0, 'DJAMEL MICHAL', '', '2018-09-30'),
(57, 'ALBRAU PACK JTL 25CL*24', '64', '110', 'bouteille', 'Biere', 150, 'DJAMEL MICHAL', '', '2018-09-30'),
(58, 'ONCV GRIS D ALGERIE ', '445', '120', 'bouteille', 'Vin', 0, 'DJAMEL MICHAL', '', '2018-09-30'),
(59, 'WHISKY BALLANTINES BTLS 1L', '1850', '4000', 'bouteille', 'Liqueur', 0, 'DJAMEL MICHAL', '', '2018-09-30'),
(60, 'WHISKY JOHNNY WALKER', '1850', '4000', 'bouteille', 'Liqueur', 0, 'DJAMEL MICHAL', '', '2018-09-30'),
(61, 'JET 27 BTLS 1', '1800', '4000', 'bouteille', 'Liqueur', 0, 'DJAMEL MICHAL', '', '2018-09-30'),
(62, 'JET 31 BTLS 1', '1900', '4000', 'bouteille', 'Liqueur', 80, 'DJAMEL MICHAL', '', '2018-09-30'),
(63, 'WHISKY G&B BTLS 1', '1950', '4000', 'bouteille', 'Liqueur', 0, 'DJAMEL MICHAL', '', '2018-09-30'),
(64, 'JACK DANIAL 1L ', '3800', '8000', 'bouteille', 'Liqueur', 0, 'DJAMEL MICHAL', '', '2018-09-30'),
(65, 'RICARD', '1300', '3200', 'bouteille', 'Liqueur', 0, 'DJAMEL MICHAL', '', '2018-09-30'),
(66, 'BEAUFORT CANNET 50CL', '116', '17000', 'bouteille', 'Biere', 0, 'DJAMEL MICHAL', '', '2018-11-02'),
(67, 'BEAUFORT JTB 25CL PACK 24', '6750', '10000', 'bouteille', 'Biere', 0, 'DJAMEL MICHAL', '', '2018-11-02'),
(68, 'ALBRAUT CAISSE 24CL', '1200', '1100', 'bouteille', 'Biere', 0, 'DJAMEL MICHAL', '', '2018-11-12'),
(69, 'ONCV MEDEA 98*50CL', '270', '800', 'bouteille', 'Vin', 0, 'DJAMEL MICHAL', '', '2018-11-15'),
(70, 'GCO ROSE FLEUR DABOUKIR 75CL', '625', '1200', 'bouteille', 'Vin', 0, 'DJAMEL MICHAL', '', '2018-11-15'),
(71, 'CABERNET CASTEL  75CL', '325', '1000', 'bouteille', 'Vin', 0, 'DJAMEL MICHAL', '', '2018-11-15'),
(72, 'MERLOT CASTEL 75CL', '325', '1000', 'bouteille', 'Vin', 50, 'DJAMEL MICHAL', '', '2018-11-15'),
(73, 'VIN CASSTILLA 12BTLS*75CL', '310', '1000', 'bouteille', 'Vin', 0, 'DJAMEL MICHAL', '', '2018-11-15'),
(74, 'ROSE CABERNET SAUNIGNION 50CL', '330', '1000', 'bouteille', 'Vin', 0, 'DJAMEL MICHAL', '', '2018-11-15'),
(75, 'VIN ROUGE FOS 2012', '525', '1200', 'bouteille', 'Vin', 0, 'DJAMEL MICHAL', '', '2018-11-15'),
(76, 'SAMBA CAISSE 24 BT', '56', '120', 'bouteille', 'Biere', 6912, 'DJAMEL MICHAL', '', '2019-03-27'),
(77, '33 EXPORT 33CL*24', '76', '140', 'bouteille', 'Biere', 96, 'DJAMEL MICHAL', '', '2019-03-28'),
(78, 'KRONOMBOURGUE 1664 PACK 24', '170', '220', 'bouteille', 'Biere', 24, 'DJAMEL MICHAL', '', '2019-03-28'),
(79, 'ALBRAUT CAISSE 24* 24CL', '50', '120', 'bouteille', 'Biere', 144, 'DJAMEL MICHAL', '', '2019-03-28'),
(80, 'HIENEKEN CAISSE 24*25CL', '116', '170', 'bouteille', 'Biere', 96, 'DJAMEL MICHAL', '', '2019-03-28'),
(81, 'BECKS CAISSE 24*24CL', '120', '150', 'bouteille', 'Biere', 72, 'DJAMEL MICHAL', '', '2019-03-28'),
(82, 'WISKY 1L', '1500', '2000', 'bouteille', 'Liqueur', 91, 'DJAMEL MICHAL', '', '2021-02-28'),
(83, 'TEST 2021', '150', '200', 'bouteille', 'Biere', 560, 'HWAMDI ', '', '2021-03-12');
--
-- end table insert : produits
--

/*!40000 ALTER TABLE `produits` ENABLE KEYS */;


--
-- start  table dump : salaires
--

CREATE TABLE IF NOT EXISTS `salaires` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_employe` int(11) NOT NULL,
  `solde` double NOT NULL,
  `date` date NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;



--
-- end  table dump : salaires
--



--
-- start  table dump : sortieproduit
--

CREATE TABLE IF NOT EXISTS `sortieproduit` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `des_prod` varchar(100) NOT NULL,
  `qte` int(11) NOT NULL,
  `prix_vente` double NOT NULL,
  `total` double NOT NULL,
  `date` date NOT NULL,
  `employe` tinyint(4) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=48 DEFAULT CHARSET=latin1;



--
-- end  table dump : sortieproduit
--


--
-- Inserts of sortieproduit
--


/*!40000 ALTER TABLE `sortieproduit` DISABLE KEYS */;

--
-- start table insert : sortieproduit
--
INSERT INTO `sortieproduit`(`id`, `des_prod`, `qte`, `prix_vente`, `total`, `date`, `employe`) VALUES 
(1, 'GCO  KOUTOUBIA12*75CL', 2, '1200', '2400', '2018-09-26', 3),
(8, 'HEINIKEN BTLS 25CL', 5, '4080', '20400', '2018-09-27', 1),
(7, 'ALBRAU CAISSE 24CL', 9, '2640', '23760', '2018-09-27', 1),
(6, '33EXPORT BTLS33CL', 5, '3360', '16800', '2018-09-27', 1),
(9, 'GCO  CUVEE TLEMCEN 12BTLS*50CL', 1, '800', '800', '2018-09-27', 1),
(10, 'BECKS PACK 50CL', 48, '4800', '230400', '2018-09-27', 3),
(11, 'KRONONBOUGUE 1664 25CL5.5*20BTLS', 15, '4400', '66000', '2018-09-27', 3),
(12, 'WHISKY JOHNNY 1L', 2, '4500', '9000', '2018-09-27', 3),
(13, 'SAMBA JET 25CL', 60, '2640', '158400', '2018-09-27', 2),
(14, 'WHISKY JACKE DANIAL 1L', 0, '9000', '0', '2018-09-27', 2),
(15, 'RICARD ', 5, '38400', '192000', '2018-09-27', 2),
(16, 'ALBRAU CAISSE 24CL', 0, '110', '0', '2018-09-30', 2),
(19, 'ALBRAU CAISSE 24CL', 0, '110', '0', '2018-11-12', 3),
(20, 'BEAUFORT CAISSE 24CL', 0, '100', '0', '2018-11-12', 3),
(21, 'SAMBA CAISSE 24CL', 0, '110', '0', '2018-11-12', 3),
(22, 'KEINEKEN BTLS 25CL', 0, '170', '0', '2018-11-12', 3),
(23, 'HEINEKEN BTLSCL 33', 0, '200', '0', '2018-11-12', 3),
(24, 'BECKS JET  BTLS 25CL', 0, '140', '0', '2018-11-12', 3),
(25, 'KOELBERG JET BTLS', 0, '140', '0', '2018-11-12', 3),
(26, '33 EXPORT  CAISSE 33CL', 0, '140', '0', '2018-11-12', 3),
(27, 'SAMBA CANETTE PACK 50CL', 0, '170', '0', '2018-11-12', 3),
(28, 'ALBRAU CANETTE  PACK 50CL', 0, '170', '0', '2018-11-12', 3),
(29, 'HEINEKEN CANETTE PACK 50CL', 0, '220', '0', '2018-11-12', 3),
(30, 'KRONOBOURG( 1664) *24BTLS', 0, '220', '0', '2018-11-12', 3),
(31, 'KRONOBOURG( 1664) *24BTLS', 0, '220', '0', '2018-11-12', 3),
(32, 'ALBRAU PACK JET 25CL', 0, '110', '0', '2018-11-12', 3),
(33, 'BECKS PACK CANETTE 50CL', 0, '200', '0', '2018-11-12', 3),
(34, 'SAMBA PACK JTL  25CL*24', 0, '110', '0', '2018-11-12', 3),
(35, 'ALBRAU PACK JTL 25CL*24', 0, '110', '0', '2018-11-12', 3),
(36, 'GCO COTEAUX DE MASCARA 12*75CL', 0, '1200', '0', '2018-11-12', 3),
(37, 'ONCV MEDEA NV AVIS ', 0, '1200', '0', '2018-11-12', 3),
(38, 'GCO CUVEE TELEMECEN 12BTLLS*75C', 0, '1000', '0', '2018-11-12', 3),
(39, 'GCO CUVEE TELMECEN 12*50CL', 0, '800', '0', '2018-11-12', 3),
(40, 'SIDI BRAHIM 6*75CL', 0, '9000', '0', '2018-11-12', 3),
(41, 'GCO KOUTOUBIA 12*50CL', 0, '800', '0', '2018-11-12', 3),
(42, 'GCO ST-AUGSTIN BTLS 12*50CL', 0, '150', '0', '2018-11-12', 3),
(43, 'GCO KOUTOUBIA 12*75CL', 0, '1200', '0', '2018-11-12', 3),
(44, 'ONCV GRIS D ALGERIE ', 0, '120', '0', '2018-11-12', 3),
(45, 'WHISKY JOHNNY WALKER', 0, '4000', '0', '2018-11-12', 3),
(46, 'WISKY 1L', 9, '2000', '18000', '2021-02-28', 4),
(47, 'TEST 2021', 40, '200', '8000', '2021-03-12', 1);
--
-- end table insert : sortieproduit
--

/*!40000 ALTER TABLE `sortieproduit` ENABLE KEYS */;


--
-- start  table dump : unites
--

CREATE TABLE IF NOT EXISTS `unites` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nom_unite` varchar(50) NOT NULL,
  `qte_unite` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=12 DEFAULT CHARSET=latin1;



--
-- end  table dump : unites
--


--
-- Inserts of unites
--


/*!40000 ALTER TABLE `unites` DISABLE KEYS */;

--
-- start table insert : unites
--
INSERT INTO `unites`(`id`, `nom_unite`, `qte_unite`) VALUES 
(1, 'bouteille', 1),
(2, 'CAISSE', 24),
(6, 'douze', 12),
(5, 'pack de 6', 6),
(9, 'caisse*20', 20),
(11, 'BOUTELLE WHISKY', 1);
--
-- end table insert : unites
--

/*!40000 ALTER TABLE `unites` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;